#!/bin/bash
# This script displays the PID of the current process

# Assign the value of the current process's PID to the variable MY_PID
MY_PID=$$

# Print the value of MY_PID
echo "The PID of this script is: $MY_PID"

